module.exports={
    USER_COLLECTION:'user',
    PRODUCT_COLLECTION:"products",
    CATOGAERY_COLLECTION:"catogaery",
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    WISH_COLLECTION:'whishlist',
    COUPON_COLLECTION:'coupon',
    ADDRESS_COLLECTION:'address'
}